server:
  port: 9999

spring:
  application:
    name: start
  config:
    import:
      - optional:application-web.yml
      - optional:application-redis.yml
      - optional:application-datasource.yml
      - optional:application-auth.yml
      - optional:application-mail.yml
  profiles:
    active: dev