server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB #单个最大文件大小
      max-request-size: 10MB #总上传的最大数据大小
  application:
    name: start
  config:
    import:
      - optional:application-web.yml
      - optional:application-redis.yml
      - optional:application-database.yml
  profiles:
    active: dev

sa-token:
  # token前缀
  token-prefix: Bearer
  jwt-secret-key: ***REMOVE_SECRET***
  token-name: Easy-Token
  # 默认30天
  timeout: 2592000
  # 关闭logo
  is-print: false