server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB #单个最大文件大小
      max-request-size: 10MB #总上传的最大数据大小
  application:
    name: start
  config:
    import:
      - optional:application-web.yml
      - optional:application-redis.yml
      - optional:application-database.yml
  profiles:
    active: dev

sa-token:
  # token前缀
  token-prefix: Bearer
  jwt-secret-key: ***REMOVE_SECRET***
  token-name: Easy-Token
  # 登录超时
  timeout: 7200
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  is-share: false
  # 关闭logo
  is-print: false
  automatic-renewal: true