server:
  port: 8888

spring:
  application:
    name: start
  config:
    import:
      - optional:application-web.yml
      - optional:application-redis.yml
      - optional:application-datasource.yml
      - optional:application-auth.yml
  profiles:
    active: dev

sa-token:
  # token前缀
  token-prefix: Bearer
  jwt-secret-key: ***REMOVE_SECRET***
  token-name: Easy-Token
  # 登录超时
  timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  is-share: false
  # 关闭logo
  is-print: false
  # 自动补充
  automatic-renewal: true