server:
  port: 8888

spring:
  application:
    name: start
  config:
    import:
      - optional:application-web.yml
      - optional:application-redis.yml
      - optional:application-datasource.yml
      - optional:application-auth.yml
  profiles:
    active: dev

sa-token:
  # 关闭logo
  is-print: false
  # token前缀
  token-prefix: Bearer
  jwt-secret-key: ***REMOVE_SECRET***
  token-name: Easy-Token
  # 登录超时
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结 （例如可以设置为 1800 代表 30 分钟内无操作就冻结）
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个token, 为 false 时每次登录新建一个 token）
  is-share: true
  # 自动续签
  automatic-renewal: true
